### ISSUE TITLE
功能询问

### ISSUE THREAD

**Issue by szsmashaka** [chaikd/vue3-label#1]
大佬能请问下这个标注框怎么能让他支持旋转啊

**Comment by chaikd** [comment]
标注框旋转功能关闭是因为多边形、折线这些如果使用fabricjs提供的旋转功能的话只能旋转不能改变点的位置，现在放开了矩形框的选中状态切换，其他类型的旋转功能后续会慢慢更新。
感谢提问。

**Comment by chaikd** [comment]
> 大佬能请问下这个标注框怎么能让他支持旋转啊

标注框旋转功能关闭是因为多边形、折线这些如果使用fabricjs提供的旋转功能的话只能旋转不能改变点的位置，现在放开了矩形框的选中状态切换，其他类型的旋转功能后续会慢慢更新。
感谢提问。

**Comment by chaikd** [comment]
Close the issue.
